name: Test and Deploy to Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: staging
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      BASE_PATH: '${{ secrets.BASE_PATH }}'
      GIT_BRANCH: ${{ secrets.GIT_BRANCH }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to Staging
        run: |
          ssh -tt -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            cd $BASE_PATH
            git pull origin staging
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            exit;
          EOF
